EPIC: B1 - Backend endpoints to toggle (PRIORITY)
ucsb-cs156-f23/proj-organic-f23-6pm-3 pull request #32
Opened 2023-11-26 11:22 UTC by bella-ward

This PR:

Adds POST endpoint for toggleAdmin and tests.
Adds POST endpoint for toggleInstructor and tests.
Adds ROLE_INSTRUCTOR to securityConfig.
Passes test coverage.

Dokku deployment: https://organic-bella-dev.dokku-07.cs.ucsb.edu/ [memory allocation issue, so dokku is not up to date yet. ]

Closes https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-3/issues/9

2023-11-26 19:30 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/organic/entities/User.java
> +// import javax.persistence.GenerationType;
```suggestion

```

2023-11-26 19:30 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/organic/entities/User.java
> +// import javax.persistence.GeneratedValue;
```suggestion

```

2023-11-26 19:30 UTC, pconrad requested changes
Please see: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-27 03:55 UTC, Garrett-Hu approved these changes
lgtm, solid tests

2023-11-27 17:48 UTC, pconrad approved these changes
LGTM

2023-11-27 17:49 UTC, merged